version: '3.9'

services:
  db:
    image: postgres:14-alpine
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres 
      - POSTGRES_DB=postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data/

  backend:
    build:
      context: .
      dockerfile: Dockerfile 

    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres 
      - POSTGRES_DB=postgres
    
    ports:
      - "8001:8000"

    volumes:
      - ./:/app/backend

    depends_on:
      - db
    

