apiVersion: apps/v1
kind: Deployment
metadata:
  name: phishing-detector
spec:
  replicas: 3
  selector:
    matchLabels:
      app: phishing-detector
  template:
    metadata:
      labels:
        app: phishing-detector
    spec:
      containers:
      - name: phishing-detector
        image: your-registry/phishing-detector:latest
        ports:
        - containerPort: 8000
        env:
        - name: ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: anthropic-secret
              key: api-key
---
apiVersion: v1
kind: Service
metadata:
  name: phishing-detector-service
spec:
  selector:
    app: phishing-detector
  ports:
  - port: 80
    targetPort: 8000
  type: LoadBalancer