# Generated by Django 4.1.13 on 2025-02-13 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="publish",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 2, 13, 15, 27, 22, 458405, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
