# Generated by Django 4.1.13 on 2025-02-17 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_post_publish"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="publish",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 2, 17, 14, 53, 10, 536393, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
