# Generated by Django 5.1.6 on 2025-02-07 09:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_app", "0002_alter_taskapp_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskapp",
            name="pub_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 2, 7, 9, 12, 47, 456457, tzinfo=datetime.timezone.utc
                ),
                verbose_name="date published",
            ),
        ),
    ]
