# Generated by Django 5.1.6 on 2025-02-07 09:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("task_app", "0005_alter_taskapp_pub_date"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TaskApp",
            new_name="Tasks",
        ),
    ]
