# Generated by Django 5.1.6 on 2025-02-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_app", "0003_taskapp_pub_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskapp",
            name="pub_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
